### PR TITLE
Remove waiting endpoint which errors in dev/production and isn't actually useful to our users

### PR DESCRIPTION
**Pull request by callunity**
Jira ticket: GP-3694

- [x] Includes a change file
~~- [ ] Updates developer documentation~~

### CODE REVIEW

**Comment by avarsava** [comment]
GP-3272 is an older ticket for a refactor of this endpoint. Why opt for removal?

**Comment by callunity** [comment]
> GP-3272 is an older ticket for a refactor of this endpoint. Why opt for removal?

The endpoint returns a 500 error for most of our deployed instances, and fixing/refactoring it isn't a high priority right now, so I figured it was best to remove the broken endpoint for now. I'm happy to link to this PR on GP-3272 to give context/the current state of the code, for when we eventually get around to it.

**Comment by avarsava** [comment]
api-docs/vidarr.json will also need to be updated to not list this endpoint in swagger

**Comment by callunity** [comment]
I've updated the API docs and left a comment on the related ticket.

**Review by avarsava — APPROVED** [review]

**Review by mlaszloffy — APPROVED** [review]

**Pull request merged**
